import authRoutes from "./authRoutes.js";
import nutriRoutes from "./nutriRoutes.js";
import nutritionRoutes from "./nutritionRoutes.js";
import profileRoutes from "./profileRoutes.js";
import userRoutes from './userRoute.js';
import adminRoutes from "./adminRoute.js";
import coachRoutes from "./coachRoute.js";
import recipeRoutes from "./recipeRoutes.js";
import mealPlanRoutes from "./mealPlanRoutes.js";
import waterRoutes from "./waterRoutes.js";
import sleepRoutes from "./sleepRoutes.js";
import exerciseRoutes from "./exerciseRoutes.js";
import workoutRoutes from "./workoutRoutes.js";
import bodyMetricsRoutes from "./bodyMetricsRoutes.js";
export { authRoutes, nutriRoutes, nutritionRoutes, profileRoutes, userRoutes, adminRoutes, coachRoutes, recipeRoutes, mealPlanRoutes, waterRoutes, sleepRoutes, exerciseRoutes, workoutRoutes, bodyMetricsRoutes };
